port: 7880
rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 60000
  use_external_ip: true
  
keys:
  devkey: secret

logging:
  level: info
  pion_level: warn

room:
  auto_create: true
  max_participants: 10
  empty_timeout: 10m

turn:
  enabled: false

webhook:
  keys:
    - devkey: secret